import React from "react";
import { Link } from "react-router-dom";
const LeftSidebar = () => (
    <div id="m_aside_left" className="m-grid__item	m-aside-left  m-aside-left--skin-dark ">
        <div id="m_ver_menu" className="m-aside-menu  m-aside-menu--skin-dark m-aside-menu--submenu-skin-dark " m-menu-vertical="1" m-menu-scrollable="0" m-menu-dropdown-timeout="500">
            <ul className="m-menu__nav ">
                <li className="m-menu__item" aria-haspopup="true"><Link to="/" className="m-menu__link "><span className="m-menu__item-here"></span><i className="m-menu__link-icon flaticon-line-graph"></i><span className="m-menu__link-text">Dashboard</span></Link></li>
                <li className="m-menu__item m-menu__item--active" aria-haspopup="true" m-menu-link-redirect="1"><Link to="/" className="m-menu__link "><span className="m-menu__item-here"></span><i className="m-menu__link-icon flaticon-suitcase" data-toggle="m-tooltip" data-placement="right" data-skin="dark" title="" data-original-title="Work Requests"></i><span className="m-menu__link-text">Work Requests</span></Link></li>
                <li className="m-menu__item" aria-haspopup="true" m-menu-link-redirect="1"><Link to="/masters/category" className="m-menu__link "><span className="m-menu__item-here"></span><i className="m-menu__link-icon flaticon-share" data-toggle="m-tooltip" data-placement="right" data-skin="dark" title="" data-original-title="Proposals"></i><span className="m-menu__link-text">Proposals</span></Link></li>
                <li className="m-menu__item" aria-haspopup="true" m-menu-link-redirect="1"><Link to="/masters/location" className="m-menu__link "><span className="m-menu__item-here"></span><i className="m-menu__link-icon la la-lightbulb-o" data-toggle="m-tooltip" data-placement="right" data-skin="dark" title="" data-original-title="Jobs"></i><span className="m-menu__link-text">Jobs</span></Link></li>
                <li className="m-menu__item" aria-haspopup="true" m-menu-link-redirect="1"><Link to="/" className="m-menu__link "><span className="m-menu__item-here"></span><i className="m-menu__link-icon flaticon-web" data-toggle="m-tooltip" data-placement="right" data-skin="dark" title="" data-original-title="Bids"></i><span className="m-menu__link-text">Bids</span></Link></li>
                <li className="m-menu__item" aria-haspopup="true" m-menu-link-redirect="1"><Link to="/" className="m-menu__link "><span className="m-menu__item-here"></span><i className="m-menu__link-icon flaticon-clipboard" data-toggle="m-tooltip" data-placement="right" data-skin="dark" title="" data-original-title="Invoices"></i><span className="m-menu__link-text">Invoices</span></Link></li>
                <li className="m-menu__item" aria-haspopup="true" m-menu-link-redirect="1"><Link to="/" className="m-menu__link "><span className="m-menu__item-here"></span><i className="m-menu__link-icon flaticon-clock-1" data-toggle="m-tooltip" data-placement="right" data-skin="dark" title="" data-original-title="Timesheets"></i><span className="m-menu__link-text">Timesheets</span></Link></li>
                <li className="m-menu__item" aria-haspopup="true" m-menu-link-redirect="1"><Link to="/" className="m-menu__link "><span className="m-menu__item-here"></span><i className="m-menu__link-icon flaticon-clock-2" data-toggle="m-tooltip" data-placement="right" data-skin="dark" title="" data-original-title="Time Reports"></i><span className="m-menu__link-text">Time Reports</span></Link></li>
                <li className="m-menu__item" aria-haspopup="true" m-menu-link-redirect="1"><Link to="/" className="m-menu__link "><span className="m-menu__item-here"></span><i className="m-menu__link-icon flaticon-cogwheel-2" data-toggle="m-tooltip" data-placement="right" data-skin="dark" title="" data-original-title="Team Scheduling"></i><span className="m-menu__link-text">Team Scheduling</span></Link></li>
                <li className="m-menu__item" aria-haspopup="true" m-menu-link-redirect="1"><Link to="/" className="m-menu__link "><span className="m-menu__item-here"></span><i className="m-menu__link-icon la la-cubes" data-toggle="m-tooltip" data-placement="right" data-skin="dark" title="" data-original-title="Timesheets"></i><span className="m-menu__link-text">Work Types</span></Link></li>
                <li className="m-menu__item" aria-haspopup="true" m-menu-link-redirect="1"><Link to="/" className="m-menu__link "><span className="m-menu__item-here"></span><i className="m-menu__link-icon la la-file-text" data-toggle="m-tooltip" data-placement="right" data-skin="dark" title="" data-original-title="Timesheets"></i><span className="m-menu__link-text">Inspections</span></Link></li>
                <li className="m-menu__item" aria-haspopup="true" m-menu-link-redirect="1"><Link to="/" className="m-menu__link "><span className="m-menu__item-here"></span><i className="m-menu__link-icon la la-building-o" data-toggle="m-tooltip" data-placement="right" data-skin="dark" title="" data-original-title="Clients"></i><span className="m-menu__link-text">Buildings</span></Link></li>
                <li className="m-menu__item" aria-haspopup="true" m-menu-link-redirect="1"><Link to="/" className="m-menu__link "><span className="m-menu__item-here"></span><i className="m-menu__link-icon flaticon-user" data-toggle="m-tooltip" data-placement="right" data-skin="dark" title="" data-original-title="Sub Contractor"></i><span className="m-menu__link-text">Subcontractor</span></Link></li>
                <li className="m-menu__item" aria-haspopup="true" m-menu-link-redirect="1"><Link to="/crew" className="m-menu__link "><span className="m-menu__item-here"></span><i className="m-menu__link-icon flaticon-user-add" data-toggle="m-tooltip" data-placement="right" data-skin="dark" title="" data-original-title="Crew"></i><span className="m-menu__link-text">Crew</span></Link></li>
            </ul>
        </div>
    </div>
);

export default LeftSidebar;